version: "3.0"
services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    # hostname: 'gitlab.devops85.com'
    # environment:
    #   GITLAB_OMNIBUS_CONFIG: |
    #     external_url 'https://gitlab.devops85.com'
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
      # - './config:/etc/gitlab'
      # - './logs:/var/log/gitlab'
      # - './data:/var/opt/gitlab'